# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf69a0ae1d5bc8571bdfc0ff4086cb5bb9986aa65c49ae312b9d1061e06c941370b9707f470f1c71dcb335f6c6fdb92ddc86b2d3ac3ca3c53a7e7e9518a41aec

test:
  secret_key_base: 9d1f2750ffc26f70c77560ac57f48d410d5a5896c9d04dddf6c793c011fca5075fed7fa070ede0319e4bc6129d02e0755531704752caeeba25d8d816b8c495a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
